### PR TITLE
adds kubernetes manifests

### PR DESCRIPTION
**Pull request by hubwoop**
Hi, thanks for the awesome container, i've deployed it on of k8s using the added manifests, if you want to use them feel free to merge...

cheers!

### CODE REVIEW

**Comment by CanadaBry** [comment]
Thanks! I'm happy to see people using it.

I'd like to merge it, but I haven't worked with kubernetes, so I wouldnt be able to write anything help in the readme for it.

**Comment by hubwoop** [comment]
Alright, maybe i'll publishi a helm chart with your container in it ;) Tahnks again!

I actually messed up and published our super secure password with this PR. I've already changed it, but would you mind deleting this PR for me 😅🙈 https://github.com/CanadaBry/ValheimDocker/pull/3/commits/2626812f39356da331e2f9823b5c5c47de15d6a9#diff-fd3123404ce56d3cd6729a0581b453f5f5464127f32487a3ee75e36c8b427496R25-R26

**Comment by CanadaBry** [comment]
Yeah I saw the server info wasnt default, so i figured that was why you closed it. I don't have access to delete the files. I havent deletes a PR before, can you tell me how? lol

**Comment by hubwoop** [comment]
I just googled this and it looks like there might be no other way than actually mailing GitHub staff about it. Which you certainly should not do because of my errors. I already made you enough work this this and changed the pw..  anyways thanks again, and sorry for the inconveniences!

**Comment by CanadaBry** [comment]
No worries. Yeah my googles said the same thing, but wanted to check if you knew something I didnt. Appreciate the feedback none-the-less, and it really wasnt an inconvenience at all.

**Pull request closed without merging**
